#!/bin/bash

options=(
    style=round
    width=4.0
    hidpi=on
    active_color=0xff3e8fb0
    # active_color=0xffea9a97
    inactive_color=0xff6e6a86
    blacklist="MacVim"
)

borders "${options[@]}"
