# Brews
brew "bash"
brew "choose-gui"
brew "clang-format"
brew "cmatrix"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "ghcup"
brew "go@1.24"
brew "hexedit"
brew "icarus-verilog"
brew "jq"
#brew "kanata"
#cargo install kanata
#cd ~/.cargo/registry/src/index.crates.io-{something}/kanata-1.8.1
#cargo install --features cmd --path . --offline
# OR
#❯ git clone https://github.com/jtroo/kanata
#❯ cargo build --release --features cmd
brew "katago"
brew "mole"
brew "mpv"
brew "neovim"
brew "octave"
brew "openjdk@25"
#brew "python@3.13"
brew "pipx"
brew "rust"
brew "ripgrep"
brew "sc-im"
brew "slides"
brew "surfer"
brew "tlrc"
brew "tmux"
brew "typst"
brew "yt-dlp"
brew "zig"

# Casks
cask "anki"
cask "bitwarden"
cask "brave-browser"
cask "docker-desktop"
cask "element"
cask "ghostty"
cask "gimp"
cask "hammerspoon"
cask "iina"
cask "karabiner-elements"
cask "obsidian"
cask "font-sf-mono"
cask "font-sf-pro"
cask "font-sketchybar-app-font"
cask "logisim-evolution"
cask "macvim-app"
cask "qutebrowser"
cask "raycast"
cask "sf-symbols"
cask "sioyek"
cask "telegram-desktop"
cask "the-unarchiver"
cask "visual-studio-code"
cask "vscodium"
cask "whatsapp"
cask "xquartz"
cask "zoom"

# Taps
tap "nikitabobko/tap"
cask "aerospace"

tap "FelixKratz/formulae"
brew "sketchybar"

cask "temurin@8"
