# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# Deprecated: see issue `https://github.com/nikitabobko/AeroSpace/issues/1482`
after-login-command = [ ]

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    'exec-and-forget sketchybar',
    'exec-and-forget ~/scripts/wifi-stat.zsh',
    'exec-and-forget open -a "Hammerspoon.app"',
    'exec-and-forget open -a "Obsidian.app"',
    'workspace t',
    'exec-and-forget open -a "Ghostty.app"',
    'exec-and-forget sudo ~/bin/kanata/target/release/kanata -c ~/.config/kanata/kanata.kbd',
]

exec-on-workspace-change = ['/bin/bash', '-c',
    #'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
    'sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE AEROSPACE_PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE',
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

[gaps]
inner.horizontal = 4
inner.vertical =   4
outer.left =       4
outer.bottom =     4
outer.top =        4
outer.right =      4

# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift


cmd-h = []
cmd-alt-h = []
cmd-m = []

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# ctrl-shift-f1 is saved for Raycast
ctrl-shift-f2 = 'mode service'
ctrl-shift-f3 = 'mode launch'
ctrl-shift-f4 = 'mode switch'
ctrl-shift-f5 = 'mode window'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']

z = ['exec-and-forget ~/scripts/toggle_zen.sh', 'mode main']

[mode.launch.binding]
t = ['workspace t', 'exec-and-forget open -a "Ghostty.app"',       'mode main']
o = ['workspace o', 'exec-and-forget open -a "Obsidian.app"',      'mode main']
b = ['workspace b', 'exec-and-forget open -a "Brave Browser.app"', 'mode main']
w = ['workspace w', 'exec-and-forget open -a "WhatsApp.app"',      'mode main']
m = ['workspace m', 'exec-and-forget open -a "Mail.app"',          'mode main']
f = ['workspace f', 'exec-and-forget open -a "Finder.app"',        'mode main']
k = ['workspace k', 'exec-and-forget open -a "Sabaki.app"',        'mode main']
v = ['workspace v', 'exec-and-forget code',                        'mode main']
p = [               'exec-and-forget open -a "Bitwarden.app"',     'mode main']
u = ['workspace u',                                                'mode main']
esc = 'mode main'

[mode.switch.binding]
t = ['move-node-to-workspace t', 'workspace t', 'mode main']
o = ['move-node-to-workspace o', 'workspace o', 'mode main']
b = ['move-node-to-workspace b', 'workspace b', 'mode main']
w = ['move-node-to-workspace w', 'workspace w', 'mode main']
m = ['move-node-to-workspace m', 'workspace m', 'mode main']
f = ['move-node-to-workspace f', 'workspace f', 'mode main']
k = ['move-node-to-workspace k', 'workspace k', 'mode main']
v = ['move-node-to-workspace v', 'workspace v', 'mode main']
u = ['move-node-to-workspace u', 'workspace u', 'mode main']
esc = 'mode main'

[mode.window.binding]
minus = 'resize smart -50'
shift-equal = 'resize smart +50'
equal = 'balance-sizes'
f = 'fullscreen'

h = 'focus left'
j = 'focus down'
k = 'focus up'
l = 'focus right'

shift-h = 'move left'
shift-j = 'move down'
shift-k = 'move up'
shift-l = 'move right'

t = 'layout tiles horizontal vertical'
a = 'layout accordion horizontal vertical'

esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['move-node-to-workspace o']

[[on-window-detected]]
if.app-id = 'net.ankiweb.launcher'
run = ['layout floating']
