#!/bin/bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
FONT="SF Mono"

source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=32 blur_radius=30 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="$FONT:Bold:17.0"
  label.font="$FONT:Bold:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=4
  icon.padding_right=8
  label.padding_left=8
  label.padding_right=4
  background.corner_radius=5
  background.height=28
  background.border_width=3
  background.color=$BG
  background.drawing=on
)
sketchybar --default "${default[@]}"

##### Left Side Items #####
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        icon.padding_left=0 \
        icon.padding_right=0 \
        background.border_color=$GREEN \
        background.drawing=off \
        background.corner_radius=0 \
        label="$sid" \
        label.padding_right=10 \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

sketchybar --add bracket aerospace '/space\..*/' \
           --set aerospace background.color=$BG \
                           background.border_width=3 \
                           background.corner_radius=4 \
                           background.border_color=$GREEN

##### Right of Notch Items #####
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/media.sh

##### Right Side Items #####
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
